--[[ commented as it has to be implemented
	btnSetSalir     = "Exit",
	btnSetContinuar = "Keep playing",
	btnFinAcabar    = "Finish",
	btnFinContinuar = "Continue"
	--<<"Welcome again! I'm going to show you now how to play at the duel mode&& The gamerules remain the same, but only two players compete&& and you win by earning 5 points.",
	--<<"Your turn! In the duel, when completing a rosebush with a majority of white portions&& you earn a tower movement point.",
	--<<"Place the tile to add a white portion and press OK",
	--<<"Very well! You've earned one tower point!",
	--<<"Let's get another tower point! Place the tile in order to complete the rosebush with majority of white portions." ,
	--<<"Press OK to confirm.",
	--<<"We already have two! After moving your soldiers you can move a tower spending one of these points. ",
	--<<"Select the tower and move it to the right place to block your opponent. ",
	--<<"Press OK to confirm your movement.",
	--<<"Good! Now the blue soldier is blockedn and he should take out the tower or go back to the reserve discarding a tile if he wants to get out. ",
	--<<"Your turn again! Place the tile with a white portion in this position to void a potential scoring of the Blue player . ",
	--<<"Press OK to confirm.",
	--<<"Cool! You see, when you complete a rosebush with an equal number of portions from each color, it becomes null point. && Use this strategy to get in your opponent's way.",
	--<<"I saw it coming ...&& Remember that you can discard a tile to send back a soldier to the reserve. ",
	--<<"By blocking your opponent you'll make him lose valuable time while you score points! Combine your second soldier and the towers to be much more effective.",
	--<<"You know everything you need to win the duel! && Remember in the duel mode you win the game by scoring just 5 points." ,
	--<<"You can also challenge your friends or other players in the online mode! Enjoy!",
	--<<"You've finished the duel mode  tutorial, do you want to continue the game until 5 points?",
]]