--[[ commented as it has to be implemented
	btnSetSalir     = "Sair do tutorial",
	btnSetContinuar = "Continuar jogando",
	btnFinAcabar    = "Acabar",
	btnFinContinuar = "Continuar",
	--<< "Bem-vindo outra vez! Agora vou ensinar como jogar ao modo duelo.&& As regras do jogo são as mesmas, mas neste modo se enfrentam dois jogadores && e ganha o jogo quem marcar 5 pontos.",
	--<< "Seu turno! No duelo, quando você completa uma roseira com a maioria de porções brancas && você ganha um ponto de movimento de torre.",
	--<< "Coloque o azulejo para adicionar uma parte branca e clique em OK",
	--<< "Muito bem! Você ganhou um ponto de torre",
	--<< "Tentemos ganhar outro ponto de torre! Coloque o azulejo para completar a roseira com a maioria de partes brancas.",
	--<< "Pulse em OK para confirmar.",
	--<< "Já temos dois! Depois de mover seus soldados, pode mover uma torre usando um destes pontos.",
	--<< "Selecione a torre e coloque-a no lugar indicado para bloquear seu oponente.",
	--<< "Clique em OK para confirmar o movimiento.",
	--<< "Perfeito! Agora o soldado azul está bloqueado. Ele deverá tirar a torre ou voltar à reserva descartando um azulejo se quiser sair de ali.",
	--<< "É seu turno outra vez! Coloque o azulejo com uma porção branca nesta posição para anular um ponto possível do jogador Azul.",
	--<< "Clique em OK para aceitar",
	--<< "Muito bem! Como você pode ver, ao completar uma roseira com um número igual de partes de cada cor, o ponto é anulado.&& Use esta estratégia para prejudicar seu rival.",
	--<< "Eu imaginava que isso fosse acontecer... && Lembre-se que você pode descartar um azulejo para pôr um soldado na reserva.",
	--<< "Bloquear seu adversário fará com que ele perca tempo enquanto você marca pontos valiosos! Combine o seu segundo soldado e as torres para ser mais eficaz.",
	l--<< "Agora você já sabe tudo o que precisa para ganhar no modo duelo! && Lembre-se que no modo duelo você vencerá a partida ao marcar 5 pontos.",
	--<< "Também pode desafiar seus amigos ou outros jogadores no modo online! Divirta-se!",
	--<< "Você acabou o tutorial do modo duelo, gostaria de continuar jogando até chegar aos 5 puntos?"
	--<< END translate >>--
]]